AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'lib/tasks/cucumber.rake'

Metrics/BlockLength:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/FormatStringToken:
  Exclude:
    - 'config/routes.rb'
