:verbose: true
# This is set to single-threaded due to an issue with thread
# safety in GovspeakRenderer.
:concurrency: 1
:logfile: ./log/sidekiq.json.log
:queues:
  - [bulk_republishing, 1]
  - [imports, 2]
  - [router, 4]
  - [panopticon, 4]
  - [publishing_api, 4]
  - [default, 5]
  - [scheduled_publishing, 10]
